#==============================O==============================#
# I---------------------------------------------------------I #
# |                Johnytech6 configuration                 | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

dm_welcome_message: Welcome back Dungeon Master!
hero_welcome_message: Welcome back hero!
default_welcome_message: Welcome hero!

# list of heros
Heros:
  defaultHero:
    PlayerUUID: defaultID

#list of dms
Dms:
  defaultDm:
    PlayerUUID: defaultID



