#==============================O==============================#
# I---------------------------------------------------------I #
# |                Johnytech6 configuration                 | #
# 1---------------------------------------------------------1 #
#==============================o==============================#


# list of heros
Heros:

#list of dms
Dms:



