main: io.github.johnytech6.JohnytechPlugin
name: Johnyetch6Plugin
version: 1.9.1
description: Plugin of Johnytech6 for fun
author: Johnytech6
website: https://github.com/Johnytech6/Johnytech6s_Plugin
api-version: 1.16
depend:
- ProtocolLib
- LibsDisguises
- Morphy
commands:
   stat_Johnytech6Plugin:
      description: See all puppeters
      usage: /stat_Johnytech6Plugin
      permission: dm.mode
   dm:
      description: Set the table room of the game
      usage: /set_dnd_room
      permission: dm.mode
   getPlayerPosition:
      description: Get the player of any player
      usage: /getPlayerPosition <player>
      permision: dm.mode
permissions:
   dm.mode.*:
      description: Toggle dm powers
      children:
         dm.mode.invisibility: true
         dm.mode.vision: true
         dm.mode.puppeter: true
         dm.mode.teft: true
      default: op
   hero.*:
      description: Hero commands
      default: true
