main: io.github.johnytech6.JohnytechPlugin
name: Johnyetch6Plugin
version: 1.8.1
description: Plugin of Johnytech6 for fun
author: Johnytech6
website: https://github.com/Johnytech6/Johnytech6s_Plugin
api-version: 1.16
depend:
- ProtocolLib
- LibsDisguises
- Morphy
commands:
   stat_Johnytech6Plugin:
      description: See all puppeters
      usage: /stat_Johnytech6Plugin
      permission: dm.mode
   dm:
      description: Set the table room of the game
      usage: /set_dnd_room
      permission: dm.mode
   dm_puppeter_toggle:
      description: Toggle the Puppeter mode
      usage: /dm_puppeter_toggle
      permission: dm.mode.puppeter
   dm_mode_toggle:
      description: Toggle the dm mode
      usage: /dm_mode_toggle
      permission: dm.mode
   dm_invisibility_toggle:
      description: Toggle the dm invisibility
      usage: /dm_invisibility_toggle
      permission: dm.mode.invisibility
   dm_vision_toggle:
      description: Toggle the dm night vision
      usage: /dm_vision_toggle
      permission: dm.mode.vision
   dm_teft_toggle:
      description: Toggle the dm teft power
      usage: /dm_teft_toggle
      permission: dm.mode.teft 
permissions:
   dm.mode.*:
      description: Toggle dm powers
      children:
         dm.mode.invisibility: true
         dm.mode.vision: true
         dm.mode.puppeter: true
         dm.mode.teft: true
      default: op
   hero.*:
      description: Hero commands
