@startuml

title __DM's Class Diagram__\n

  namespace io.github.johnytech6 {
    namespace dm {
      class io.github.johnytech6.dm.Dm {
          - chairPosition : Location
          - checkpoint : Location
          - hasNightVision : boolean
          - hasPuppeterPower : boolean
          - hasTeftPower : boolean
          {static} - hh : HeroHandler
          - isInvisible : boolean
          - isVerbose : boolean
          - playerRef : Player
          {static} - plugin : Plugin
          + Dm()
          + Dm()
          + addPotionEffect()
          + getChairPosition()
          + getCheckpoint()
          + getLocation()
          + getName()
          + getPlayer()
          + getUniqueId()
          + hasChair()
          + hasCheckpoint()
          + hasNightVision()
          + hasPotionEffect()
          + hasPuppeterPower()
          + hasTeftPower()
          + invisibilityToggle()
          + isInvisible()
          + isVerbose()
          + loadConfig()
          + nightVisionToggle()
          + removePotionEffect()
          + sendMessage()
          + sendTitle()
          + setAllPower()
          + setChairPosition()
          + setCheckpoint()
          + setGameMode()
          + setInvisibility()
          + setNightVision()
          + setPuppeterPower()
          + setTeftPower()
          + setVerbose()
          + teleport()
      }

      class io.github.johnytech6.dm.VirtualInventory {
          - inventoryRef : Inventory
          - viewer : Player
          - virtualInventory : Inventory
          + VirtualInventory()
          + getInventory()
          + getViewer()
          + getVirtualInventory()
      }
    }
  }
  

  io.github.johnytech6.dm.Dm .up.|> io.github.johnytech6.DndPlayer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
