main: com.DjembeInc.johnytechPlugin.JohnytechPlugin
name: MorphyPuppeter
version: 1.2
description: Plugin of Jeanla6 for fun
author: Johnytech6
website: https://github.com/Johnytech6/Johnytech6s_Plugin
api-version: 1.15
depend:
 - ProtocolLib
 - LibsDisguises
 - Morphy
commands:
  see_puppeters:
    description: See all puppeters
    usage: /see_puppeters
  toggle_puppeter_mode:
    description: Toggle the Puppeter mode
    usage: /toggle_puppeter_modes
