@startuml
left to right direction
skinparam style strictuml
skinparam packageStyle rect
skinparam defaultfontname Verdana
actor Dm as dm
rectangle "PluginHandler" {
  (Morph into Entity) as JP #PowderBlue
  (Leave Entity) as R #PowderBlue
  dm -- JP
  dm -- R
}
@enduml