@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS - Control Mobs
actor ":Dm" as dm
participant ":PluginHandler" as plugin

dm -> plugin : morph(puppet :Entity)

return Control of Entity (movement)

opt player toggle sneak
dm -> plugin : unMorph()
return Dm leave mobs and become invisible
end opt


@enduml