@startuml MDD
skinparam style strictuml
skinparam defaultfontname Verdana
hide empty members
left to right direction
title Domain model of Johnytech6's plugin

class "PluginHandler" as ph

class "DMHandler" as dmh

class "HeroHandler" as hh

class "PuppeterHandler" as puh

class "DndPlayer" as dndP{
playerReference :Player
chair_location :Location
checkpoint_location :Location
}

class "Dm" as dm{
    isInvisible :boolean
    hasNightVision :boolean
    hasPuppeterPower :boolean
    hasTeftPower :boolean
}

class "Hero" as h{
    frozenState :boolean
}

class "Session" as ses{
    isStarted: boolean
}

class "Teft" as t

class "Puppeter" as pupter{
wasInvisible : boolean
hasNightVision : boolean
}

class "Puppet" as pup{
entity_reference : Entity
}

ph "1" -- "1" dmh

ph "1" -- "1" hh

ph "1" -- "1" puh

ph "1" -- "1" ses : host

ph "1" -right- "1.*" dndP : save

dndP "1" -- "1" dm : is a <
dndP "1" -- "1" h : is a <

dm "1" -- "1" pupter : can be a

dm  --  ses : "start"
dm  --  ses : "end"

dm "1" -- "1" t : can be a

pupter "1" -right- "1"  pup : control a

right footer
Made by Johnytech6
end footer

@enduml