@startuml

title __PUPPETER's Class Diagram__\n

  namespace io.github.johnytech6 {
    namespace dm {
      namespace puppeter {
        class io.github.johnytech6.dm.puppeter.Puppet {
            - boots : ItemStack
            - chestplate : ItemStack
            - entityRef : Entity
            - helmet : ItemStack
            - itemInMainHand : ItemStack
            - iteminOffHand : ItemStack
            - leggins : ItemStack
            + Puppet()
            + getBoots()
            + getChestplate()
            + getEntity()
            + getHelmet()
            + getItemInMainHand()
            + getItemInOffHand()
            + getLeggings()
            + setBoots()
            + setChestplate()
            + setHelmet()
            + setItemInMainHand()
            + setItemInOffHand()
            + setLeggings()
        }
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace dm {
      namespace puppeter {
        class io.github.johnytech6.dm.puppeter.Puppeter {
            - index : int
            - playerRef : Player
            + Puppeter()
            + getIndex()
            + getName()
            + getPlayer()
            + getPuppet()
            + setIndex()
            + setPuppet()
        }
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace dm {
      namespace puppeter {
        class io.github.johnytech6.dm.puppeter.PuppeterHandler {
            {static} - dmh : DMHandler
            - morphedPuppeters : ArrayList<Puppeter>
            - puppeters : ArrayList<Puppeter>
            {static} - single_instance : PuppeterHandler
            + AddMorphPuppeter()
            + AddPuppeter()
            + GetMorphPuppeter()
            + Morph()
            + MorphInArmorStand()
            + RemoveMorphPlayer()
            + RemovePuppeter()
            + TogglePuppeterMode()
            + Unmorph()
            + UnmorphMob()
            + UnmorphOfArmorStand()
            {static} + getInstance()
            + getMorphPlayers()
            + getPuppeter()
            + getPuppeters()
            + isPlayerMorph()
            + isPlayerPuppeter()
            + setPuppeterMode()
            - PuppeterHandler()
            - giveArmorOfAT()
            - itemInHand()
            - removeEquipmentFromAS()
            - storeArmorStandEquipment()
        }
      }
    }
  }
  

  io.github.johnytech6.dm.puppeter.Puppeter o-- io.github.johnytech6.dm.puppeter.Puppet : puppet


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
