@startuml

title __PUPPETER's Class Diagram__\n

  namespace io.github.johnytech6 {
    namespace dm {
      namespace puppeter {
        class io.github.johnytech6.dm.puppeter.Puppet {
            - boots : ItemStack
            - chestplate : ItemStack
            - entityRef : Entity
            - helmet : ItemStack
            - itemInMainHand : ItemStack
            - iteminOffHand : ItemStack
            - leggins : ItemStack
            + Puppet()
            + getBoots()
            + getChestplate()
            + getEntity()
            + getHelmet()
            + getItemInMainHand()
            + getItemInOffHand()
            + getLeggings()
            + setBoots()
            + setChestplate()
            + setHelmet()
            + setItemInMainHand()
            + setItemInOffHand()
            + setLeggings()
        }
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace dm {
      namespace puppeter {
        class io.github.johnytech6.dm.puppeter.Puppeter {
            - hadNightVision : boolean
            - playerRef : Player
            - wasInvisibile : boolean
            + Puppeter()
            + getName()
            + getPlayer()
            + getPuppet()
            + getUniqueId()
            + hadNightVision()
            + setInvisibilityState()
            + setNightVisionState()
            + setPuppet()
            + wasInvisible()
        }
      }
    }
  }
  

  io.github.johnytech6.dm.puppeter.Puppeter o-- io.github.johnytech6.dm.puppeter.Puppet : puppet


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
