@startuml

title __HANDLER's Class Diagram__\n

  namespace io.github.johnytech6 {
    namespace Handler {
      class io.github.johnytech6.Handler.DMHandler {
          - dms : ArrayList<Dm>
          - isSessionStarted : boolean
          {static} - ph : PluginHandler
          - plugin : Plugin
          {static} - pph : PuppeterHandler
          {static} - single_instance : DMHandler
          {static} - th : TeftHandler
          + ToggleDmMode()
          + addDm()
          + endSession()
          + getDm()
          + getDms()
          {static} + getInstance()
          + isPlayerDm()
          + isSessionStarted()
          + removeDm()
          + setDmMode()
          + startSession()
          - DMHandler()
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace Handler {
      class io.github.johnytech6.Handler.HeroHandler {
          - heros : ArrayList<Hero>
          {static} - ph : PluginHandler
          {static} - plugin : Plugin
          {static} - single_instance : HeroHandler
          + addHero()
          + freezeAllHeros()
          + getHero()
          + getHeros()
          {static} + getInstance()
          + isPlayerHero()
          + removeHero()
          + unfreezeAllHeros()
          - HeroHandler()
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace Handler {
      class io.github.johnytech6.Handler.PluginHandler {
          {static} - dmh : DMHandler
          - dndPlayers : ArrayList<DndPlayer>
          {static} - hh : HeroHandler
          - offlineDndPlayers : ArrayList<OfflineDndPlayer>
          {static} - pph : PuppeterHandler
          {static} - single_instance : PluginHandler
          {static} - th : TeftHandler
          + addDndPlayer()
          + getDndPlayer()
          + getDndPlayers()
          {static} + getInstance()
          + getOfflineDndPlayer()
          + getofflineDndPlayers()
          + isOfflineDndPlayers()
          + isPlayerDndPlayer()
          + johnytech6Stat()
          + loadConfig()
          + removeDndPlayer()
          + removeOfflineDndPlayers()
          - PluginHandler()
      }
    }
  }
  

  namespace io.github.johnytech6 {
    namespace Handler {
      class io.github.johnytech6.Handler.TeftHandler {
          {static} - dmh : DMHandler
          {static} - single_instance : TeftHandler
          - tefts : ArrayList<Teft>
          + AddTeftPlayer()
          + RemoveTeftPlayer()
          + ToggleTeftMode()
          {static} + getInstance()
          + getTeft()
          + getTeftPlayers()
          + isPlayerTeft()
          + setTeftMode()
          - TeftHandler()
      }
    }
  }
  

  io.github.johnytech6.Handler.DMHandler o-- io.github.johnytech6.Handler.HeroHandler : hh


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
